AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Athletes to College Portal
Globals:
  Function:
    Runtime: python3.7
    Timeout: 30
Resources:
  displayPortalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      CodeUri: ./athlete/
      Events:
        displayPortalApi:
          Type: Api
          Properties:
            Path: /
            Method: get
        updatePortalApi:
          Type: Api
          Properties:
            Path: /
            Method: post
