---
version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --region us-east-1 --template-file UI/samTemplate.yaml --s3-bucket a2c-src-530317771161 --output-template-file UI/samTemplateOut.yaml
artifacts:
  type: zip
  files:
    - UI/samTemplateOut.yaml
