AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Athletes to College Portal
Globals:
  Function:
    Runtime: python3.7
    Timeout: 30
Resources:
  athleteApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionUrl: ./athlete/a2c-API-dev-swagger.yaml
      Auth:
        DefaultAuthorizer: a2cCognitoAuthorizer
        Authorizers:
          a2cCognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:us-east-1:530317771161:userpool/us-east-1_DOD7SyKZu
  coachApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionUrl: ./coach/coacha2c-API-dev-swagger.yaml
      Auth:
        DefaultAuthorizer: a2cCognitoAuthorizer
        Authorizers:
          a2cCognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:us-east-1:530317771161:userpool/us-east-1_DOD7SyKZu
  loginApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionUrl: ./login/logina2c-API-dev-swagger.yaml
  displayPortalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      CodeUri: ./athlete/
      Events:
        displayPortalApi:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref athleteApi
        updatePortalApi:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId: !Ref athleteApi
  coachPortalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: coach_function.lambda_handler
      CodeUri: ./coach/
      Events:
        displayCoachPortal:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref coachApi
  loginPortalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: login_function.lambda_handler
      CodeUri: ./login/function.zip
      Events:
        formPortalApi:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref loginApi
        loginPortalApi:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId: !Ref loginApi
