AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Athletes to College Portal
Globals:
  Function:
    Runtime: python3.7
    Timeout: 30
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-729d3814
  CognitoDomain:
    Type: String
    Default: thefirmu
  ContentUrl:
    Type: String
    Default: "https://devportal.thefirmu.org"
Mappings:
  VPC2Subnet:
    vpc-729d3814:
      Subnets:
        - "subnet-76ade63f"
        - "subnet-8c44d6d7"
        - "subnet-be65cf82"
Resources:
  LambdaForCloudFormation:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: LambdaForCloudFormation
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Action: 'sts:AssumeRole'
            Principal:
              Service: lambda.amazonaws.com
      Policies:
        -
          PolicyName: WriteCloudWatchLogs
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              -
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
        -
          PolicyName: UpdateUserPoolClient
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              -
                Effect: Allow
                Action: 'cognito-idp:UpdateUserPoolClient'
                Resource: 'arn:aws:cognito-idp:*:*:userpool/*'
        -
          PolicyName: ManageUserPoolDomain
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              -
                Effect: Allow
                Action: 'cognito-idp:CreateUserPoolDomain'
                Resource: 'arn:aws:cognito-idp:*:*:userpool/*'
              -
                Effect: Allow
                Action: 'cognito-idp:DeleteUserPoolDomain'
                Resource: 'arn:aws:cognito-idp:*:*:userpool/*'
              -
                Effect: Allow
                Action: 'cognito-idp:DescribeUserPoolDomain'
                Resource: '*'
        -
          PolicyName: InvokeLambdaFunction
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              -
                Effect: Allow
                Action: 'lambda:InvokeFunction'
                Resource: 'arn:aws:lambda:*:*:function:*'
  CloudFormationSendResponse:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: CloudFormationSendResponse
      Runtime: nodejs8.10
      Code: ./CloudFormationSendResponse
      Handler: index.handler
      Role: !GetAtt LambdaForCloudFormation.Arn
  CloudFormationCognitoUserPoolClientSettings:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: CloudFormationCognitoUserPoolClientSettings
      Runtime: nodejs8.10
      Code: ./CloudFormationCognitoUserPoolClientSettings.js
      Handler: CloudFormationCognitoUserPoolClientSettings.handler
      Role: !GetAtt LambdaForCloudFormation.Arn
    DependsOn: CloudFormationSendResponse
  CloudFormationCognitoUserPoolDomain:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: CloudFormationCognitoUserPoolDomain
      Runtime: nodejs8.10
      Code: ./CloudFormationCognitoUserPoolDomain.js
      Handler: CloudFormationCognitoUserPoolDomain.handler
      Role: !GetAtt LambdaForCloudFormation.Arn
    DependsOn: CloudFormationSendResponse
  theFirmuCognitoPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
         AllowAdminCreateUserOnly: True
         InviteMessageTemplate:
           EmailMessage: "Welcome to The Firmu!  Below you will find your username and temporary password.  Please go to https://devportal.thefirmu.org to change your password.\n\nYour username is {username} and temporary password is {####}. \n\nThank you for being a member of The FirmU!"
           EmailSubject: "Welcome to The FirmU!"
      AutoVerifiedAttributes:
        - email
      DeviceConfiguration:
        ChallengeRequiredOnNewDevice: False
        DeviceOnlyRememberedOnUserPrompt: False
      EmailConfiguration:
        EmailSendingAccount: DEVELOPER
        ReplyToEmailAddress: admin@thefirmu.org
        SourceArn: !Join ['',['arn:aws:ses:',!Ref "AWS::Region",':',!Ref "AWS::AccountId",':identity/admin@thefirmu.org']]
      EmailVerificationMessage: "Your FirmU verification code is {####}. Please go to https://devportal.thefirmu.org"
      EmailVerificationSubject: "Your FirmU verification code"
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: True
          RequireNumbers: True
          RequireSymbols: True
          RequireUppercase: True
          TemporaryPasswordValidityDays: 7
      Schema:
        - AttributeDataType: String
          Mutable: True
          Name: email
          Required: True
      UserPoolName: "thefirmu"
  mgmtPortalCognitoPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "thefirmu.cognito.allow"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        -
          Effect: Allow
          Action: ['cognito-idp:AdminInitiateAuth', 'cognito-idp:AdminCreateUser']
          Resource: !GetAtt ['theFirmuCognitoPool','Arn']
      Roles:
        - !ImportValue 'a2c-mgmt-stack-MgmtRole'
  theFirmuCognitoClientSettings:
    Type: 'Custom::CognitoUserPoolClientSettings'
    Properties:
      ServiceToken: !GetAtt CloudFormationCognitoUserPoolClientSettings.Arn
      UserPoolId: !Ref theFirmuCognitoPool
      UserPoolClientId: !Ref theFirmuMgmtCognitoClient
      SupportedIdentityProviders:
        - COGNITO
      CallbackURL: !Join ['',[!Ref ContentUrl,', https://',!GetAtt ['LoadBalancer','DNSName'],'/oauth2/idpresponse, ',!Ref ContentUrl,'/oauth2/idpresponse, https://',!GetAtt ['LoadBalancer','DNSName']]]
      LogoutURL: !Ref ContentUrl
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
  theFirmuDomain:
    Type: 'Custom::CognitoUserPoolDomain'
    Properties:
      ServiceToken: !GetAtt CloudFormationCognitoUserPoolDomain.Arn
      UserPoolId: !Ref theFirmuCognitoPool
      Domain: !Ref CognitoDomain
  displayPortalRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: a2c-role
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Statement:
        -
          Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: ['sts:AssumeRole']
  displayPortalDynamoPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "a2c.dynamo.allow"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        -
          Effect: Allow
          Action: [ "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:GetItem",
                "dynamodb:Scan",
                "dynamodb:Query",
                "dynamodb:UpdateItem"
          ]
          Resource: !ImportValue 'a2c-mgmt-stack-DynamoDBARN'
      Roles:
        - !Ref "displayPortalRole"
  displayPortalCognitoPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "a2c.cognito.allow"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        -
          Effect: Allow
          Action: ['cognito-idp:AdminInitiateAuth', 'cognito-idp:AdminCreateUser']
          Resource: !Ref theFirmuCognitoPool
      Roles:
        - !Ref "displayPortalRole"
  displayPortalSSMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "a2c.ssm.allow"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        -
          Effect: Allow
          Action: ['ssm:GetParameter']
          Resource: !Join ['',['arn:aws:ssm:',!Ref 'AWS::Region',':',!Ref 'AWS::AccountId',':parameter/a2c/*']]
      Roles:
        - !Ref "displayPortalRole"
  theFirmuCognitoClient:
    Type: AWS::Cognito::UserPoolClient
    Properties: 
      ClientName: athlete
      ExplicitAuthFlows: 
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: True
      RefreshTokenValidity: 30
      UserPoolId: !Ref theFirmuCognitoPool
  theFirmuMgmtCognitoClient:
    Type: AWS::Cognito::UserPoolClient
    Properties: 
      ClientName: mgmt
      ExplicitAuthFlows: 
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: True
      RefreshTokenValidity: 30
      UserPoolId: !Ref theFirmuCognitoPool
  cognitoPoolSSM:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: /a2c/dev/cognito_pool
      Type: String
      Value: !Ref theFirmuCognitoPool
  cognitoClientIdSSM:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: /a2c/dev/athlete_cognito_client_id
      Type: String
      Value: !Ref theFirmuCognitoClient
  cognitoClientIdSSM:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: /a2c/dev/mgmt_cognito_client_id
      Type: String
      Value: !Ref theFirmuMgmtCognitoClient
  cognitoAuthUrlSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /a2c/dev/cognito_auth_url
      Type: String
      Value: !Join ['',['https://',!Ref CognitoDomain,'.auth.us-east-1.amazoncognito.com/oath2/']]
  cognitoContentUrlSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /a2c/dev/content_url
      Type: String
      Value: !Join ['',[!Ref ContentUrl,'/']]`
  displayPortalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      CodeUri: ./athlete/
      Role: !GetAtt ["displayPortalRole","Arn"]
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing 
      Subnets: !FindInMap [VPC2Subnet, !Ref "VpcId", Subnets]
      SecurityGroups:
      - !Ref LoadBalancerSecurityGroup
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: LambdaInvokePermission
    Properties:
      TargetType: lambda
      Targets:
      - Id: !GetAtt displayPortalFunction.Arn
  HttpsListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
      - TargetGroupArn: !Ref TargetGroup
        Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Certificates: 
      - CertificateArn: 'arn:aws:acm:us-east-1:530317771161:certificate/192967f9-e1f8-4fb4-8d1d-c1ab00381c4d'
      Port: 443
      Protocol: HTTPS
  ListenerCert:
    Type: AWS::ElasticLoadBalancingV2::ListenerCertificate
    Properties: 
      Certificates: 
      - CertificateArn: 'arn:aws:acm:us-east-1:530317771161:certificate/192967f9-e1f8-4fb4-8d1d-c1ab00381c4d'
      ListenerArn: !Ref HttpsListener
  CognitoListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties: 
      Actions: 
        - Type: authenticate-cognito
          AuthenticateCognitoConfig:
            UserPoolArn: !Ref theFirmuCognitoPool
            UserPoolClientId: !Ref theFirmuCognitoClient
            UserPoolDomain: "thefirmu"
          Order: 1
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
          Order: 2
      Conditions: 
        - Field: path-pattern
          Values: [ "/" ]
      ListenerArn: !Ref HttpsListener
      Priority: 1
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http(s) to client host
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt displayPortalFunction.Arn
      Action: 'lambda:InvokeFunction'
      Principal: elasticloadbalancing.amazonaws.com
Outputs:
  LoadBalancerDns:
    Description: DNS entry for Load Balancer
    Value: !GetAtt ["LoadBalancer","DNSName"]
    Export:
      Name: !Sub "${AWS::StackName}-LBDnsName"
