AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Verifies an account
Globals:
  Function:
    Runtime: python3.7
    Timeout: 30
Resources:
  verifyAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      CodeUri: ./
      Events:
        verifyAccountApi:
          Type: Api
          Properties:
            Path: /
            Method: get
