AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Athletes to College Portal
Globals:
  Function:
    Runtime: python3.7
    Timeout: 30
Resources:
  displayCoachFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: coach_function.lambda_handler
      CodeUri: ./
      Events:
        displayCoachApi:
          Type: Api
          Properties:
            Path: /
            Method: get
